export const PHONE_COUNTRY_CODES = [
  { code: "+506", country: "CR" },
  { code: "+1", country: "US/CA" },
  { code: "+52", country: "MX" },
  { code: "+57", country: "CO" },
  { code: "+51", country: "PE" },
  { code: "+54", country: "AR" },
  { code: "+55", country: "BR" },
  { code: "+56", country: "CL" },
  { code: "+34", country: "ES" },
  { code: "+33", country: "FR" },
  { code: "+49", country: "DE" },
  { code: "+44", country: "UK" },
  { code: "+39", country: "IT" },
  { code: "+31", country: "NL" },
  { code: "+41", country: "CH" },
  { code: "+61", country: "AU" },
  { code: "+81", country: "JP" },
  { code: "+82", country: "KR" },
  { code: "+86", country: "CN" },
  { code: "+91", country: "IN" },
] as const;
